##  Array by Row Iterator

This demo creates a custom iterator to return rows of an array.  Normally this is useless, array rows can be accessed directly by index. The use case here is an operation performed on rows of an array that we want to map() (from multiprocessing.Pool) onto multiple cores.  In this case we need an iterator to access the rows of the array that we can pass to map().

In [25]:
import numpy as np

In [26]:
a=np.random.randn(10,3)

In [27]:
print (a.shape)

(10, 3)


In [28]:
class ArrayByRow(object):
    def __init__(self, a):
        self.array = a
        self.index = 0
        self.length = a.shape[0]        
    #  Python 3: __iter__  Python 2: iter
    def __iter__(self): return self
    def __next__(self):
        if self.index >= self.length:
            raise StopIteration
        this_one = self.index
        self.index += 1
        return self.array[this_one,:]

In [29]:
aRow = ArrayByRow(a)

In [30]:
for i,r in enumerate(aRow):
    print ('Index {} Value {}\n'.format(i,r))

Index 0 Value [-0.49980766 -1.38302651  0.11533487]

Index 1 Value [-0.26821221 -1.09012698 -1.70011212]

Index 2 Value [ 0.83645504  1.96788311  0.50168339]

Index 3 Value [ 1.10545827 -0.54970285  1.35990934]

Index 4 Value [ 2.39269104 -0.00784193 -0.45178302]

Index 5 Value [-0.94832246  0.8582951  -0.04908127]

Index 6 Value [ 0.96308198  1.49324459  0.81817845]

Index 7 Value [-1.19327438 -1.05849623  0.1907277 ]

Index 8 Value [-0.3760167  -0.3819627   0.82390703]

Index 9 Value [ 0.90575049  1.48050448 -1.29303415]



In [31]:
print(a)

[[-0.49980766 -1.38302651  0.11533487]
 [-0.26821221 -1.09012698 -1.70011212]
 [ 0.83645504  1.96788311  0.50168339]
 [ 1.10545827 -0.54970285  1.35990934]
 [ 2.39269104 -0.00784193 -0.45178302]
 [-0.94832246  0.8582951  -0.04908127]
 [ 0.96308198  1.49324459  0.81817845]
 [-1.19327438 -1.05849623  0.1907277 ]
 [-0.3760167  -0.3819627   0.82390703]
 [ 0.90575049  1.48050448 -1.29303415]]
